#! /bin/sh

### BEGIN INIT INFO
# Provides:          blinknetworkled
# Required-Start:    
# Required-Stop:
# Should-Start:      $all
# Default-Start: 2 3 4 5    
# Default-Stop: 0 1 6
# Short-Description: set blue LED to timer trigger
# Description: Blink the blue LED on cubieboard when system is going up.
#	This LED is controlled by ifplugdown later show morse code
### END INIT INFO

N=/etc/init.d/blinknetworkled

set -e

case "$1" in
  start)
	echo -n timer > /sys/class/leds/blue\:ph21\:led2/trigger
	;;
  stop|reload|restart|force-reload|status)
	echo -n 0 > /sys/class/leds/blue\:ph21\:led2/brightness
	;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
