#! /bin/sh

### BEGIN INIT INFO
# Provides:          cubian-resize2fs
# Required-Start:    $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     S   
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO

set -e

screen_print(){
printf "$1" > /dev/tty0
}

N=/etc/init.d/cubian-resize2fs

case "$1" in
  start)
		screen_print "Resizing partitions, please wait"
	    /sbin/resize2fs /dev/mmcblk0p1 &&
		/sbin/insserv -r cubian-resize2fs &&
		screen_print "........done\n"
        ;;
  *)
        echo "Usage: $N {start}" >&2
        exit 1
        ;;
esac

exit 0
