#! /bin/sh

### BEGIN INIT INFO
# Provides:          cubian-bootled
# Required-Start:    
# Required-Stop:
# Should-Start:      $all
# Default-Start:     2 3 4 5    
# Default-Stop:      0 1 6
# Short-Description: Let the green led on cubieboard indicate booting status
# Description:       Blink the green led on cubieboard when system is going down or starting up.
#	                 Use the green LED light indicates the SD-card when system started up
### END INIT INFO

N=/etc/init.d/cubian-bootled

set -e

case "$1" in
  start)
	echo -n "mmc0" > /sys/class/leds/green\:ph20\:led1/trigger
	;;
  stop|reload|restart|force-reload|status)
    echo -n "timer" > /sys/class/leds/green\:ph20\:led1/trigger
	;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac
exit 0
