#! /bin/sh

### BEGIN INIT INFO
# Provides:          cubianinit
# Required-Start:    
# Required-Stop:
# Should-Start:      $all
# Default-Start: 2 3 4 5    
# Default-Stop: 0 1 6
# Short-Description: Other Cubian init scripts
# Description: Other Cubian init scripts
### END INIT INFO

N=/etc/init.d/cubianinit

set -e

case "$1" in
  start)
	sysctl -w "kernel.printk=3 4 1 3"
	;;
  *)
	echo "Usage: $N {start}" >&2
	exit 1
	;;
esac

exit 0
