#! /bin/bash -e

### BEGIN INIT INFO
# Provides:          cubian-bootled
# Required-Start:    
# Required-Stop:
# Should-Start:      $all
# Default-Start:     2 3 4 5    
# Default-Stop:      0 1 6
# Short-Description: Let the green led on cubieboard indicate booting status
# Description:       Blink the green led on cubieboard when system is going down or starting up.
#	                 Use the green LED light indicates the SD-card when system started up
### END INIT INFO
source /lib/lsb/init-functions
N=/etc/init.d/cubian-bootled
LED=/sys/class/leds/green\:ph20\:led1/

case "$1" in
  start)
	if [ ! -d $LED ];then
		log_failure_msg "$LED not exist"
		exit 2
	fi
	echo -n "mmc0" > ${LED}/trigger
	;;
  stop|reload|restart|force-reload|status)
	if [ ! -d $LED ];then
		log_failure_msg "$LED not exists"
		exit 2
	fi
    echo -n "timer" > ${LED}/trigger
	;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac
exit 0
