#! /bin/sh

### BEGIN INIT INFO
# Provides:          bootled
# Required-Start:    
# Required-Stop:
# Should-Start:      $all
# Default-Start: 2 3 4 5    
# Default-Stop: 0 1 6
# Short-Description: Let the green led on cubieboard indicate booting status
# Description: Blink the green led on cubieboard when system is going down or starting up.
#	Turn off the green LED light when system started up
### END INIT INFO

N=/etc/init.d/bootled

set -e

case "$1" in
  start)
	# close green led when system has start up
        echo 0 > /sys/class/leds/green\:ph20\:led1/brightness
	;;
  stop|reload|restart|force-reload|status)
        echo timer > /sys/class/leds/green\:ph20\:led1/trigger
	;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
