#! /bin/bash -e

### BEGIN INIT INFO
# Provides:          cubian-blinknetworkled 
# Required-Start:    
# Required-Stop:
# Should-Start:
# X-Start-Before:    $ifplugd
# Default-Start:     2 3 4 5    
# Default-Stop:      0 1 6
# Short-Description: set blue LED to timer trigger
# Description:       Blink the blue LED on cubieboard 
#                    When system is going up.This LED is 
#                    controlled by ifplugdown later show 
#                    morse code
### END INIT INFO
source /lib/lsb/init-functions
N=/etc/init.d/cubian-blinknetworkled
LED=/sys/class/leds/blue\:ph21\:led2/

case "$1" in
  start)
	if [ ! -d $LED ];then
		log_failure_msg "$LED not exist"
		exit 2
	fi
	echo -n timer > ${LED}/trigger
	;;
  stop|reload|restart|force-reload|status)
	if [ ! -d $LED ];then
		log_failure_msg "$LED not exists"
		exit 2
	fi
	echo -n 0 > ${LED}/brightness
	;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
