#! /bin/bash

### BEGIN INIT INFO
# Provides:          cubian-fixrandomemac
# Required-Start:    $local_fs
# Required-Stop:
# Should-Start:   
# X-Start-Before:    $networking
# Default-Start:     S    
# Default-Stop:
# Short-Description: Fix random emach on cubieboard
# Description:       Always respect the emac which is setted by script.bin
#                    Otherwise generate a mac address to be used every time
#
#                    Refs:
#                    http://linux-sunxi.org/EMAC
#                    This will cause some problems, see
#                    https://github.com/cubieplayer/Cubian/issues/63
#                    https://github.com/cubieplayer/Cubian/issues/47
#
### END INIT INFO

N=/etc/init.d/cubian-fixrandomemac

set -e

SCRIPT_BIN="/boot/script.bin"
CUBIAN_EMAC="/root/.cubian-emac"
IF="eth0"
HAS_SUNXI_EMAC=
EMAC=

if [ -f $SCRIPT_BIN ];then
	bin2fex $SCRIPT_BIN 2>/dev/null | grep -qi "^\s*MAC\s*=" && \
	HAS_SUNXI_EMAC=true || HAS_SUNXI_EMAC=false
else
	echo "$N warning: script.bin not found"
	HAS_SUNXI_EMAC=false
fi

setEmac(){
if [ ! -f $CUBIAN_EMAC ];then
randemac="c0:b0:$(openssl rand -hex 4 | sed 's/\(..\)/\1:/g; s/.$//')"
echo "$N generate mac address $emac to $CUBIAN_EMAC"
cat > $CUBIAN_EMAC <<END
$randemac
END
EMAC="$randemac"
else
EMAC=$(cat $CUBIAN_EMAC)
fi
}

case "$1" in
  start)
	    if ! $HAS_SUNXI_EMAC;then
			setEmac
			set +e
			echo "$N set mac address $EMAC on ${IF}"
			/sbin/ifconfig $IF hw ether $EMAC
			if [ "$?" != "0" ];then
				echo "$N error: invalid mac address format? check file $CUBIAN_EMAC"
			fi
		fi
        ;;
  *)
        echo "Usage: $N {start}" >&2
        exit 1
        ;;
esac

exit 0
