#! /bin/sh

### BEGIN INIT INFO
# Provides:          cubian-gpiopermission
# Required-Start:    
# Required-Stop:
# Should-Start:      $all
# Default-Start:     2 3 4 5    
# Default-Stop:
# Short-Description: Fix GPIO permission issue
# Description:       Some gpio interface belongs to root by default.
#                    Change it to gpio group.
### END INIT INFO

N=/etc/init.d/cubian-gpiopermission

set -e

case "$1" in
  start)
	chgrp -R gpio /sys/class/gpio
	chmod -R g+rw /sys/class/gpio
	find /sys/class/leds -maxdepth 1 -follow -type d | sed "s/\$/\//" | xargs chgrp -R gpio
	find /sys/class/leds -maxdepth 1 -follow -type d | sed "s/\$/\//" | xargs chmod -R g+rw
	;;
  *)
	echo "Usage: $N {start}" >&2
	exit 1
	;;
esac

exit 0
