#! /bin/sh

### BEGIN INIT INFO
# Provides:          cubian-cpufreq
# Required-Start:    
# Required-Stop:
# Should-Start:      $all
# Default-Start: 2 3 4 5    
# Default-Stop:
# Short-Description: Adjust cpu frequency
# Description: Adjust CPU freqency on system up
### END INIT INFO

N=/etc/init.d/cubian-cpufreq

set -e

case "$1" in
  start)
	for cpu in $(ls /sys/devices/system/cpu/ | grep 'cpu[0-9][0-9]*');do
	  echo -n performance > /sys/devices/system/cpu/${cpu}/cpufreq/scaling_governor
	  echo -n 1008000 > /sys/devices/system/cpu/${cpu}/cpufreq/scaling_max_freq
	  echo -n 300000 > /sys/devices/system/cpu/${cpu}/cpufreq/scaling_min_freq
	done

	;;
  status)
	cpufreq-info
	;;
  *)
	echo "Usage: $N {start|status}" >&2
	exit 1
	;;
esac

exit 0
