#! /bin/sh

### BEGIN INIT INFO
# Provides:          cubian-fixrandomemac
# Required-Start:    $network
# Required-Stop:
# Should-Start:   
# Default-Start:     2 3 4 5    
# Default-Stop:
# Short-Description: Fix random emach on cubieboard
# Description:       Always respect the emac which is setted by script.bin
#                    Otherwise use the current emach to be static.
### END INIT INFO

N=/etc/init.d/cubian-fixrandomemac

set -e

SCRIPT_BIN="/boot/script.bin"
SUNXI_EMAC_FIX="/etc/dhcp/dhclient-enter-hooks.d/fixrandomemac"
HAS_SUNXI_EMAC=

if [ -f $SCRIPT_BIN ];then
	bin2fex $SCRIPT_BIN 2>/dev/null | grep -qi "^\s*MAC\s*=" && \
	HAS_SUNXI_EMAC=true || HAS_SUNXI_EMAC=false
else
	echo "$N warning: script.bin not found"
	HAS_SUNXI_EMAC=false
fi

fixSunxiEmac(){
currentEmac=$(ifconfig | grep eth0 | awk '{print $5}')
echo "$N fix random emac using $currentEmac"
cat > $SUNXI_EMAC_FIX <<END
#!/bin/bash
#
# By default the EMAC driver uses a random MAC address each boot
# http://linux-sunxi.org/EMAC
# 
# This will cause some problems, see
# https://github.com/cubieplayer/Cubian/issues/63
# https://github.com/cubieplayer/Cubian/issues/47
#
/sbin/ifconfig eth0 hw ether $currentEmac
END
}

case "$1" in
  start)
	    if $HAS_SUNXI_EMAC;then
			if [ -f $SUNXI_EMAC_FIX ];then
				echo "$N using emac setting from $SCRIPT_BIN"
				rm -fv $SUNXI_EMAC_FIX
			fi
		else
			if [ ! -f $SUNXI_EMAC_FIX ];then
				fixSunxiEmac
			fi
		fi
        ;;
  *)
        echo "Usage: $N {start}" >&2
        exit 1
        ;;
esac

exit 0
