#! /bin/sh

### BEGIN INIT INFO
# Provides:          gpiopermission
# Required-Start:    
# Required-Stop:
# Should-Start:      $all
# Default-Start: 2 3 4 5    
# Default-Stop:
# Short-Description: Fix GPIO permission issue
# Description: /sys/class/gpio belongs to root by default, change it to gpio group
### END INIT INFO

N=/etc/init.d/gpiopermission

set -e

case "$1" in
  start)
	chgrp -R gpio /sys/class/gpio
	chmod -R g+rw /sys/class/gpio
	;;
  *)
	echo "Usage: $N {start}" >&2
	exit 1
	;;
esac

exit 0
