#!/bin/bash
ipaddr=`/usr/lib/cubian/cubian-getip`
lockfile=/var/lock/cubian-morsemsg.lock
if [ "$ipaddr" != '' ];then
    if [ -f $lockfile ];then
        rm -f $lockfile
    fi
    /usr/lib/cubian/cubian-morsemsg $ipaddr
fi
