#!/bin/bash
ipaddr=`/usr/lib/cubian/cubian-getip`
ipaddr_reversed=`echo $ipaddr | rev`
lockfile='/var/lock/cubian-morsemsg'
if [ "$ipaddr" != '' ];then
    if [ -f $lockfile ];then
        rm -f $lockfile
    fi
    /usr/lib/cubian/cubian-morsemsg $ipaddr_reversed
fi
