#! /bin/bash
set -e

# Warning:
# this program is designed exec by at command, don't use STDOUT in the program
# STDOUT,STDERROR will be mailed to /var/mail/

BLUE_LED=/sys/class/leds/blue\:ph21\:led2/
GREEN_LED=/sys/class/leds/green\:ph20\:led1/
BLUE_LED_BRIGHTNESS=${BLUE_LED}/brightness
GREEN_LED_BRIGHTNESS=${GREEN_LED}/brightness
DELAY=${1:-0}
LOCK=/var/lock/cubian-networklight.lock

log(){
logger -t "networklight" "$1"
}


if [ -f $LOCK ];then
	exit 0
fi

echo $$ > $LOCK
sleep 1

[ "x$(cat $LOCK)" == "x"$$ ] || exit

if [ ! -d $BLUE_LED ] || [ ! -d $GREEN_LED ];then
	log "$0 execuate failed, led doesn't exists"
	exit 2
fi
echo -n 0 > ${BLUE_LED}/brightness
log "wait interfaces ready, waiting $DELAY seconds"
sleep $DELAY
log "start probe interfaces"
set +e
for interface in $(ls /sys/class/net/ | grep -v 'lo\|tunl[0-9][0-9]*\|gre[0-9][0-9]*\|ip6tnl[0-9][0-9]*\|sit[0-9][0-9]*\|p2p[0-9][0-9]*');do
    hasNetWork=$(cat /sys/class/net/$interface/carrier 2>/dev/null)
    if [[ "$hasNetWork" = "1" ]];then
        log "network interface $interface online"
        break
    else
        log "network interface $interface offline"
    fi
done
set -e

if [[ "$hasNetWork" = "1" ]];then
    echo -n 0 > $BLUE_LED_BRIGHTNESS
    echo -n 0 > $GREEN_LED_BRIGHTNESS
	log "Waiting IP address for 20 seconds"
    sleep 20
    #indicates the morse code start to begin
    echo -n 1 > $GREEN_LED_BRIGHTNESS
    sleep 3
    echo -n 0 > $GREEN_LED_BRIGHTNESS
    echo -n 0 > $BLUE_LED_BRIGHTNESS

    sleep 3
	if [ "x`/usr/lib/cubian/cubian-getip`" = "x" ];then
    	log "No IPv4 address available"
    	echo -n timer > ${BLUE_LED}/trigger
	else
    	log "start show ip address by morse code through led"
    	log "IP address `/usr/lib/cubian/cubian-getip`"
    	/etc/init.d/cubian-bootled start
    	/usr/lib/cubian/cubian-morseshowip-reversed
	fi
else
    log "all the interfaces are offline"
    echo -n timer > ${BLUE_LED}/trigger
fi
rm -f $LOCK
echo "Quit"

exit 0
