#!/bin/bash
ipaddr=`/usr/lib/cubian/cubian-getip`
ipaddr_reversed=`echo $ipaddr | rev`
lockfile=/var/lock/cubian-morsemsg.lock
if [ -n "$ipaddr" ];then
    if [ -f $lockfile ];then
        rm -f $lockfile
    fi
    /bin/bash /usr/lib/cubian/cubian-morsemsg $ipaddr_reversed
fi
