#!/bin/sh

N=/etc/motd.package
L=/var/lock/update-motd-package-info

if [ -f $N ];then
cat $N >> /var/run/motd.dynamic
fi

if [ ! -f $L ];then
#this process is daemon
echo "/usr/lib/cubian/cubian-motd-package" | at now 2>/dev/null
touch $L
fi
