#!/bin/sh

N=/etc/motd.package
L=/var/lock/update-motd-package-info

if [ -f $N ];then
cat $N >> /var/run/motd.dynamic
fi

if [ ! -f $L ];then
#this process is daemon
#since cubieboard don't have rtc, use network timing instead, the time delay is not working actually, the command will execute once the ntpdate is successfull
echo "/usr/lib/cubian/cubian-motd-package" | at now + 5 min 2>/dev/null
touch $L
fi
