#!/bin/bash

screen_print(){
printf "$1" > /dev/tty0
}

is_server(){
	if [ -e /dev/fb0 ];then
		return 1
	fi
	return 0
}

if [ "$1" = "tty2" ];then
    # don't clean screen on tty2 Alt+F2
    exec /sbin/agetty $@ --noclear
	exit 0
fi

if [ -f /root/.firstRun ];then
  # clear screen
  screen_print "\033[2J\033[1;1H"
  # remove first run flag
  if is_server;then
	/bin/rm /root/.firstRun 2>/dev/null
    exec /sbin/agetty $@ --noclear --login-pause
  else
	# agetty commands must in one single file
    exec /sbin/agetty -n -l /usr/sbin/cubian-config-login $@
  fi
  exit 0
fi

exec /sbin/agetty $@
